### ISSUE TITLE
AVF Batch Converter silently fails for large dimensions

### ISSUE THREAD

**Issue by bangnoise** [Vidvox/hap-in-avfoundation#19] opened 2018-08-09 23:17 UTC
Converting the attached 16K ProRes 4444 movie to Hap Q Alpha produces an empty movie without an error message.

1. The file should correctly encode to Hap Q Alpha
2. When an error does occur, this should be conveyed to the user

[Hap_PR_05s.mov.zip](https://github.com/Vidvox/hap-in-avfoundation/files/2276128/Hap_PR_05s.mov.zip)

**Comment by mrRay** [comment] 2018-08-10 16:01
thanks for reporting this- the actual error appears to be a bug in AVFoundation (AVAssetReader doesn't work on- at the very least- ProRes movies with large resolutions like this...hit me up if you'd like to see the sample app i whipped up and double-check this).  Interestingly, if you already have a hap file at this res, the batch converter will transcode it to other hap codecs without error- so the problem is probably in the specific codec implementation, rather than AVF.

anyway, this bug appears to have been fixed in 10.14- the batch exporter successfully transcodes the sample movie you sent us.

> When an error does occur, this should be conveyed to the user

good point, i'll get right on that!

**Comment by bangnoise** [comment] 2018-08-12 19:37
Great - I get the red error status

**Comment by dlublin** [comment] 2018-09-14 20:55
Given that this is fixed on Apple's end in 10.14 and Ray has added the error status, I am closing out this issue!

**Closed by dlublin** 2018-09-14 20:55 UTC
